let Race = {
	'HUMAN': 0,
	'ELF': 1,
	'DARKELF': 2,
	'ORC': 3,
	'DWARF': 4,
	'KAMAEL': 5,
	'ERTHEIA': 6,
	'ANIMAL': 7,
	'BEAST': 8,
	'BUG': 9,
	'CASTLE_GUARD': 10,
	'CONSTRUCT': 11,
	'DEMONIC': 12,
	'DIVINE': 13,
	'DRAGON': 14,
	'ELEMENTAL': 15,
	'ETC': 16,
	'FAIRY': 17,
	'GIANT': 18,
	'HUMANOID': 19,
	'MERCENARY': 20,
	'NONE': 21,
	'PLANT': 22,
	'SIEGE_WEAPON': 23,
	'UNDEAD': 24,
	'FRIEND': 25
};
module.exports = Race;