let ZoneId = {
	'PVP': 0,
	'PEACE': 1,
	'SIEGE': 2,
	'MOTHER_TREE': 3,
	'CLAN_HALL': 4,
	'LANDING': 5,
	'NO_LANDING': 6,
	'WATER': 7,
	'JAIL': 8,
	'MONSTER_TRACK': 9,
	'CASTLE': 10,
	'SWAMP': 11,
	'NO_SUMMON_FRIEND': 12,
	'FORT': 13,
	'NO_STORE': 14,
	'SCRIPT': 15,
	'HQ': 16,
	'DANGER_AREA': 17,
	'ALTERED': 18,
	'NO_BOOKMARK': 19,
	'NO_ITEM_DROP': 20,
	'NO_RESTART': 21,
	'SAYUNE': 22,
	'FISHING': 23,
	'UNDYING': 24,
	'TAX': 25
};
module.exports = ZoneId;